export default function Page() {
  return <>
<a className="skip-link" href="#contenido">Saltar al contenido</a><header className="header"><a href="/" className="wordmark">CARMEN LLOSA</a><nav aria-label="Navegación principal"><a href="/" aria-current="page">SOBRE MÍ</a><a href="/mi-escritura/">MIS TEXTOS</a><a href="/inspiracion/">INSPIRACIÓN</a><a href="/contacto/">CONTACTO</a></nav></header><main id="contenido"><section className="cover shell"><div className="cover-copy"><p className="eyebrow">ESCRITURA CREATIVA</p><h1>¡Hola!<br/>Soy Carmen.</h1><p className="cover-intro">Me gusta que mi apellido<br/>rime con graciosa.</p><p className="home-note">Escribo sobre lo cotidiano. Que, bien mirado, tiene bastante guion.</p></div><div className="cover-aside"><img src="/images/pdf-cover.jpg" alt="Carmen sentada ante una estantería de revistas" width="923" height="1170" fetchPriority="high"/></div></section><section id="sobre-mi" className="section shell about">        <div className="about-body"><div className="bio">
          <h2 className="eyebrow bio-label">UN POCO SOBRE MÍ</h2>
          <p>Curiosa, alegre y observadora, tengo debilidad por el arte y la estética. Me apasionan el cine, la literatura, la moda y, desde la cuna, la buena mesa.</p>
          <p>Estudié ADE porque tenía salidas laborales. Entre tanto, algunos veranos ayudaba en el restaurante familiar y afinaba el paladar. Empecé a trabajar en finanzas, pero pronto entendí que necesitaba un entorno más creativo.</p>
          <p>Así llegué al idílico mundo de la moda, donde he pasado más de siete años en distintos departamentos. Los últimos cuatro, en Celia B: una empresa con tantas capas como colores.</p>
          <p>La escritura fue llegando por su cuenta. Contaba pequeñas anécdotas en Instagram, escribía cartas a mis amigos —puede que a algunos amores— y, por supuesto, despotricaba de vez en cuando en diarios. Así fui encontrando mi tono: irónico, cotidiano, ligero y con referencias pop. Todo lo esperable de una millennial.</p>
          <p>Después di con Nora Ephron y me tatué —figuradamente— eso de que todo es material para escribir.</p>
          <p>Y es lo que hago hoy. Escribo en La Soga Cultural y, más recientemente, en Substack. También he colaborado con proyectos de gastronomía y moda. Además, por casualidades de la vida —o quizá por mi gracia—, participo en algún que otro podcast.</p>
        </div><figure className="about-figure"><img className="about-photo" src="/images/pdf-about.jpg" alt="Carmen sentada a una mesa con mantel de cuadros" width="689" height="1041" loading="lazy"/><figcaption>La buena mesa viene de familia.</figcaption></figure></div>
        <details id="formacion" className="formation"><summary>En qué me formé <span aria-hidden="true">+</span></summary><ul className="education"><li><span className="date">MAYO–JULIO 2026</span><div>Curso de Periodismo en Moda, Belleza y Estilo de Vida<span className="school">Vogue College of Fashion</span></div></li><li><span className="date">2015–2016</span><div>MBA en Dirección y Gestión de Empresas de Moda<span className="school">Esden Business School</span></div></li><li><span className="date">2010–2014</span><div>Grado en Administración y Dirección de Empresas<span className="school">Universidad de Oviedo</span></div></li></ul></details>
</section></main><footer className="site-footer shell"><span>Carmen Llosa · Escritura creativa</span><a href="/mi-escritura/">Leer mis textos ↗</a></footer>
  </>;
}
