export default function Home() {
  return <>
    <a className="skip-link" href="#contenido">Saltar al contenido</a>
    <header className="header"><a href="#inicio" className="wordmark">CARMEN LLOSA</a><nav aria-label="Navegación principal"><a href="#sobre-mi">SOBRE MÍ</a><a href="#escritura">MIS TEXTOS</a><a href="#inspiracion">MI INSPIRACIÓN</a><a href="#contacto">CONTACTO</a></nav></header>
    <main id="contenido">
      <section id="inicio" className="cover shell">
        <div className="cover-aside"><img src="/images/pdf-cover.jpg" alt="Carmen sentada ante una estantería de revistas" width="923" height="1170" fetchPriority="high"/></div>
        <div className="cover-copy"><p className="eyebrow">ESCRITURA CREATIVA</p><h1>CARMEN<br/>LLOSA</h1><p className="cover-intro">Escribo sobre lo cotidiano.<br/>Que, bien mirado, tiene bastante guion.</p><a className="text-link" href="#articulos">Leer mis textos <span aria-hidden="true">↗</span></a></div>
      </section>
      <section id="sobre-mi" className="section shell about">
        <div className="section-heading"><p className="eyebrow">SOBRE MÍ</p><h2>¡Hola! Soy Carmen.</h2></div>
        <div className="about-body"><div className="bio">
          <p className="lead">Me gusta que mi apellido rime con graciosa.</p>
          <p>Curiosa, alegre y observadora, tengo debilidad por el arte y la estética. Me apasionan el cine, la literatura, la moda y, desde la cuna, la buena mesa.</p>
          <p>Estudié ADE porque tenía salidas laborales. Entre tanto, algunos veranos ayudaba en el restaurante familiar y afinaba el paladar. Empecé a trabajar en finanzas, pero pronto entendí que necesitaba un entorno más creativo.</p>
          <p>Así llegué al idílico mundo de la moda, donde he pasado más de siete años en distintos departamentos. Los últimos cuatro, en Celia B: una empresa con tantas capas como colores.</p>
          <p>La escritura fue llegando por su cuenta. Contaba pequeñas anécdotas en Instagram, escribía cartas a mis amigos —puede que a algunos amores— y, por supuesto, despotricaba de vez en cuando en diarios. Así fui encontrando mi tono: irónico, cotidiano, ligero y con referencias pop. Todo lo esperable de una millennial.</p>
          <p>Después di con Nora Ephron y me tatué —figuradamente— eso de que todo es material para escribir.</p>
          <p>Y es lo que hago hoy. Escribo en La Soga Cultural y, más recientemente, en Substack. También he colaborado con proyectos de gastronomía y moda. Además, por casualidades de la vida —o quizá por mi gracia—, participo en algún que otro podcast.</p>
        </div><figure className="about-figure"><img className="about-photo" src="/images/pdf-about.jpg" alt="Carmen sentada a una mesa con mantel de cuadros" width="689" height="1041" loading="lazy"/><figcaption>La buena mesa viene de familia.</figcaption></figure></div>
        <section id="formacion" className="formation"><h3 className="eyebrow">EN QUÉ ME FORMÉ</h3><ul className="education"><li><span className="date">MAYO–JULIO 2026</span><div>Curso de Periodismo en Moda, Belleza y Estilo de Vida<span className="school">Vogue College of Fashion</span></div></li><li><span className="date">2015–2016</span><div>MBA en Dirección y Gestión de Empresas de Moda<span className="school">Esden Business School</span></div></li><li><span className="date">2010–2014</span><div>Grado en Administración y Dirección de Empresas<span className="school">Universidad de Oviedo</span></div></li></ul></section>
      </section>
      <section id="escritura" className="section shell writing-group">
        <div className="section-heading"><p className="eyebrow">MI ESCRITURA</p><h2>Lo cotidiano da para mucho.</h2></div>
        <div className="writing-overview"><div className="writing-intro"><section className="voice"><h3 className="eyebrow">QUÉ ENCONTRARÁS EN MIS TEXTOS</h3><p className="lead">Autoironía, vida cotidiana y referencias pop. Con humor y alguna que otra reflexión.</p><p>Cine, moda, gastronomía y lo que se cruce por el camino.</p></section><section className="outlets"><h3 className="eyebrow">DÓNDE ESCRIBO</h3><ul className="publications"><li><a href="https://lasoga.org/author/carmen/">La Soga Cultural ↗</a><span>2025–actualidad</span></li><li><a href="https://substack.com/@carmenllosa">Substack ↗</a><span>2026–actualidad</span></li><li><a href="https://www.instagram.com/carmen.llosa/">Instagram ↗</a><span>2021–actualidad</span></li><li>Newsletter de Celia B<span>2024–2025</span></li></ul></section></div><img className="writing-photo" src="/images/pdf-writing.jpg" alt="Carmen escribiendo en un balcón" width="780" height="1170" loading="lazy"/></div>
        <section id="articulos" className="selected-work"><div className="work-heading"><p className="eyebrow">UNA SELECCIÓN DE TEXTOS</p><h3>Supongo que debería mostrarte algo.</h3><p>Ahí vamos.</p></div><div className="articles">
          <article><p className="article-meta">VIDA COTIDIANA · LA SOGA CULTURAL</p><h4><a href="https://lasoga.org/manual-para-sobrevivir-sola/">Manual para (sobre)vivir sola</a></h4><p>Reflexiones y consejos para cualquier mujer que quiera independizarse. Porque vivir sola también tiene su ciencia.</p><a className="text-link" href="https://lasoga.org/manual-para-sobrevivir-sola/">Leer el texto <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">CINE · LA SOGA CULTURAL</p><h4><a href="https://lasoga.org/en-defensa-de-la-comedia-romantica/">En defensa de la comedia romántica</a></h4><p>Defendí —era necesario— las comedias románticas. Alguien tenía que hacerlo.</p><a className="text-link" href="https://lasoga.org/en-defensa-de-la-comedia-romantica/">Leer el texto <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">GASTRONOMÍA · OKAERI LAB</p><h4><a href="https://okaerilab.com/category/autores/carmen-llosa/">Entre fogones y buenos guisos</a></h4><p>Me atreví con la crítica gastronómica. Haber nacido entre fogones y buenos guisos puede que tenga algo que ver.</p><a className="text-link" href="https://okaerilab.com/category/autores/carmen-llosa/">Ver mis colaboraciones <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">MODA Y MEMORIA · SUBSTACK</p><h4><a href="https://substack.com/home/post/p-211066813">Una historia de la camiseta de rayas</a></h4><p>Mi pasión por la moda me llevó a recorrer la historia de la camiseta de rayas. Y, ya que estaba, le puse un filtro autobiográfico.</p><a className="text-link" href="https://substack.com/home/post/p-211066813">Leer el texto <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">MODA Y CINE · CELIA B / INSTAGRAM</p><h4><a href="https://www.instagram.com/p/DPO_M6iigF8/?img_index=1">Hasta siempre, Robert</a></h4><p>Me despedí de Robert Redford con un pequeño homenaje en la newsletter de Celia B y en Instagram.</p><a className="text-link" href="https://www.instagram.com/p/DPO_M6iigF8/?img_index=1">Ver el homenaje <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">CINE · LINKEDIN</p><h4><a href="https://lnkd.in/p/eNP-XApu">Y, por supuesto, Diane</a></h4><p>Y, como no podía ser menos, también escribí unas palabras para despedirme de Diane Keaton.</p><a className="text-link" href="https://lnkd.in/p/eNP-XApu">Ver el homenaje <span aria-hidden="true">↗</span></a></article>
        </div></section>
      </section>
      <section id="inspiracion" className="section shell inspiration"><div className="section-heading"><p className="eyebrow">MI INSPIRACIÓN</p><h2>Todo esto también soy yo.</h2><p>Cine, libros, sobremesas y otras obsesiones.</p></div><img className="inspiration-collage" src="/images/pdf-inspiration.jpg" alt="Collage de referencias de Carmen: cine, moda, arte, gastronomía y literatura" width="2584" height="1278" loading="lazy"/></section>
    </main>
    <footer id="contacto" className="section shell"><p className="eyebrow">CUANDO CARMEN CONOCIÓ TU IDEA.</p><h2><a href="mailto:carmenllosac@gmail.com">Si te apetece,<br/>escríbeme :)</a></h2><div className="contact"><a href="mailto:carmenllosac@gmail.com">carmenllosac@gmail.com</a><a href="tel:+34654910959">654 910 959</a></div><a className="back-top" href="#inicio">Volver al principio ↑</a></footer>
  </>;
}
