export default function Page() {
  return <>
<a className="skip-link" href="#contenido">Saltar al contenido</a><header className="header"><a href="/" className="wordmark">CARMEN LLOSA</a><nav aria-label="Navegación principal"><a href="/">SOBRE MÍ</a><a href="/formacion/">FORMACIÓN</a><a href="/mi-escritura/" aria-current="page">MIS TEXTOS</a><a href="/inspiracion/">INSPIRACIÓN</a><a href="/contacto/">CONTACTO</a></nav></header><main id="contenido">      <section id="escritura" className="section shell writing-group">
        <div className="section-heading"><p className="eyebrow">MI ESCRITURA</p><h1>Lo cotidiano da para mucho.</h1></div>
        <div className="writing-overview"><div className="writing-intro"><section className="voice"><h2 className="eyebrow">QUÉ ENCONTRARÁS EN MIS TEXTOS</h2><p className="lead">Autoironía, vida cotidiana y referencias pop. Con humor y alguna que otra reflexión.</p><p>Cine, moda, gastronomía y lo que se cruce por el camino.</p></section><section className="outlets"><h2 className="eyebrow">DÓNDE ESCRIBO</h2><ul className="publications"><li><a href="https://lasoga.org/author/carmen/">La Soga Cultural ↗</a><span>2025–actualidad</span></li><li><a href="https://substack.com/@carmenllosa">Substack ↗</a><span>2026–actualidad</span></li><li><a href="https://www.instagram.com/carmen.llosa/">Instagram ↗</a><span>2021–actualidad</span></li><li>Newsletter de Celia B<span>2024–2025</span></li></ul></section></div></div>
        <section id="articulos" className="selected-work"><div className="work-heading"><p className="eyebrow">UNA SELECCIÓN DE TEXTOS</p><h2>Supongo que debería mostrarte algo.</h2><p>Ahí vamos.</p></div><div className="articles">
          <article><p className="article-meta">VIDA COTIDIANA · LA SOGA CULTURAL</p><h3><a href="https://lasoga.org/manual-para-sobrevivir-sola/">Manual para (sobre)vivir sola</a></h3><p>Reflexiones y consejos para cualquier mujer que quiera independizarse. Porque vivir sola también tiene su ciencia.</p><a className="text-link" href="https://lasoga.org/manual-para-sobrevivir-sola/">Leer el texto <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">CINE · LA SOGA CULTURAL</p><h3><a href="https://lasoga.org/en-defensa-de-la-comedia-romantica/">En defensa de la comedia romántica</a></h3><p>Defendí —era necesario— las comedias románticas. Alguien tenía que hacerlo.</p><a className="text-link" href="https://lasoga.org/en-defensa-de-la-comedia-romantica/">Leer el texto <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">GASTRONOMÍA · OKAERI LAB</p><h3><a href="https://okaerilab.com/category/autores/carmen-llosa/">Entre fogones y buenos guisos</a></h3><p>Me atreví con la crítica gastronómica. Haber nacido entre fogones y buenos guisos puede que tenga algo que ver.</p><a className="text-link" href="https://okaerilab.com/category/autores/carmen-llosa/">Ver mis colaboraciones <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">MODA Y MEMORIA · SUBSTACK</p><h3><a href="https://substack.com/home/post/p-211066813">Una historia de la camiseta de rayas</a></h3><p>Mi pasión por la moda me llevó a recorrer la historia de la camiseta de rayas. Y, ya que estaba, le puse un filtro autobiográfico.</p><a className="text-link" href="https://substack.com/home/post/p-211066813">Leer el texto <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">MODA Y CINE · CELIA B / INSTAGRAM</p><h3><a href="https://www.instagram.com/p/DPO_M6iigF8/?img_index=1">Hasta siempre, Robert</a></h3><p>Me despedí de Robert Redford con un pequeño homenaje en la newsletter de Celia B y en Instagram.</p><a className="text-link" href="https://www.instagram.com/p/DPO_M6iigF8/?img_index=1">Ver el homenaje <span aria-hidden="true">↗</span></a></article>
          <article><p className="article-meta">CINE · LINKEDIN</p><h3><a href="https://lnkd.in/p/eNP-XApu">Y, por supuesto, Diane</a></h3><p>Y, como no podía ser menos, también escribí unas palabras para despedirme de Diane Keaton.</p><a className="text-link" href="https://lnkd.in/p/eNP-XApu">Ver el homenaje <span aria-hidden="true">↗</span></a></article>
        </div></section>
      </section>
</main><footer className="site-footer shell"><span>Carmen Llosa · Escritura creativa</span><a href="/">Volver a sobre mí ↗</a></footer>
  </>;
}
