export default function Page() {
  return <>
<a className="skip-link" href="#contenido">Saltar al contenido</a><header className="header"><a href="/" className="wordmark">CARMEN LLOSA</a><nav aria-label="Navegación principal"><a href="/">SOBRE MÍ</a><a href="/formacion/">TRAYECTORIA</a><a href="/mi-escritura/" aria-current="page">ARTÍCULOS</a><a href="/contacto/">CONTACTO</a></nav></header><main id="contenido">      <section id="escritura" className="section shell writing-group">
        <h1 className="sr-only">Artículos</h1>
        
        <section id="articulos" className="selected-work"><div className="articles"><article className="article-card"><a className="article-image-link" href="https://lasoga.org/en-defensa-de-enviar-cartas/" aria-label="En defensa de enviar cartas" tabIndex={-1}><img className="article-image image-cartas" src="/images/articles/cartas.jpg" alt="Anne Bancroft ante una máquina de escribir en 84 Charing Cross Road" width="1000" height="778"/></a><p className="article-meta">ARTE Y LETRAS · LA SOGA CULTURAL</p><h2><a href="https://lasoga.org/en-defensa-de-enviar-cartas/">En defensa de enviar cartas</a></h2></article>
<article className="article-card"><a className="article-image-link" href="https://lasoga.org/manual-para-sobrevivir-sola/" aria-label="Manual para (sobre)vivir sola" tabIndex={-1}><img className="article-image image-sola" src="/images/articles/sola.jpg" alt="Carrie Bradshaw escribiendo frente a su ordenador" width="960" height="720" fetchPriority="high"/></a><p className="article-meta">VIDA COTIDIANA · LA SOGA CULTURAL</p><h2><a href="https://lasoga.org/manual-para-sobrevivir-sola/">Manual para (sobre)vivir sola</a></h2></article>
<article className="article-card"><a className="article-image-link" href="https://lasoga.org/en-defensa-de-la-comedia-romantica/" aria-label="En defensa de la comedia romántica" tabIndex={-1}><img className="article-image image-romantica" src="/images/articles/romantica.jpg" alt="Meg Ryan y Billy Crystal en Cuando Harry encontró a Sally" width="960" height="720" fetchPriority="high"/></a><p className="article-meta">CINE · LA SOGA CULTURAL</p><h2><a href="https://lasoga.org/en-defensa-de-la-comedia-romantica/">En defensa de la comedia romántica</a></h2></article>
<article className="article-card"><a className="article-image-link" href="https://okaerilab.com/cronica-culinaria-de-la-relaciones-publicas-de-okaeri-por-carmen-llosa/" aria-label="Crónica culinaria de Okaeri" tabIndex={-1}><img className="article-image image-okaeri" src="/images/articles/okaeri-people.jpg" alt="Dos personas conversando detrás de la barra de Okaeri" width="960" height="720" loading="lazy"/></a><p className="article-meta">GASTRONOMÍA · OKAERI LAB</p><h2><a href="https://okaerilab.com/cronica-culinaria-de-la-relaciones-publicas-de-okaeri-por-carmen-llosa/">Crónica culinaria de Okaeri</a></h2></article>
<article className="article-card"><a className="article-image-link" href="https://carmenllosa.substack.com/p/breve-historia-sobre-la-camiseta" aria-label="Breve historia de la camiseta de rayas" tabIndex={-1}><img className="article-image image-rayas" src="/images/articles/rayas.jpg" alt="Ilustración de una camiseta de rayas junto a una ventana al mar" width="960" height="720" loading="lazy"/></a><p className="article-meta">MODA E HISTORIA · SUBSTACK</p><h2><a href="https://carmenllosa.substack.com/p/breve-historia-sobre-la-camiseta">Breve historia de la camiseta de rayas</a></h2></article>
<article className="article-card"><a className="article-image-link" href="https://www.instagram.com/p/DPO_M6iigF8/?img_index=1" aria-label="Robert siempre será eterno" tabIndex={-1}><img className="article-image image-robert" src="/images/articles/robert-phone.webp" alt="Robert Redford hablando por teléfono en una redacción" width="960" height="720" loading="lazy"/></a><p className="article-meta">MODA Y CINE · CELIA B · INSTAGRAM</p><h2><a href="https://www.instagram.com/p/DPO_M6iigF8/?img_index=1">Robert siempre será eterno</a></h2></article>
<article className="article-card"><a className="article-image-link" href="https://lnkd.in/p/eNP-XApu" aria-label="Estilo: Celia Bernardo vs Diane Keaton" tabIndex={-1}><img className="article-image image-diane" src="/images/articles/diane-annie.jpg" alt="Diane Keaton en Annie Hall, con sombrero, chaleco y corbata" width="960" height="720" loading="lazy"/></a><p className="article-meta">MODA Y CINE · CELIA B · LINKEDIN</p><h2><a href="https://lnkd.in/p/eNP-XApu">Estilo: Celia Bernardo vs Diane Keaton</a></h2></article></div></section>
      </section>
</main><footer className="site-footer shell"><a href="/">Volver a sobre mí</a></footer>
  </>;
}
