import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source=fs.readFileSync(path.join(root,'app/page.tsx'),'utf8');
let body=source.slice(source.indexOf('return <>')+9,source.lastIndexOf('</>;'));
body=body.replaceAll('className=','class=').replaceAll('fetchPriority=','fetchpriority=');
let count=0;
body=body.replace(/src="(\/images\/[^\"]+)"/g,(_,file)=>{count++;return 'src="data:image/jpeg;base64,'+fs.readFileSync(path.join(root,'public',file)).toString('base64')+'"'});
let css=fs.readFileSync(path.join(root,'app/globals.css'),'utf8').split('\n').filter(x=>!x.startsWith('@import')&&!x.startsWith('@theme')).join('\n');
css=css.replace(/url\("(\/fonts\/[^\"]+)"\)/g,(_,file)=>'url("data:font/ttf;base64,'+fs.readFileSync(path.join(root,'public',file)).toString('base64')+'")');
const html='<!doctype html>\n<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Carmen Llosa · Escritura creativa</title><meta name="description" content="Carmen Llosa. Escritura creativa."><style>'+css+'</style></head><body>'+body+'</body></html>';
fs.writeFileSync(path.join(root,'..','Carmen-Llosa-portfolio.html'),html);
if(/className=|\/images\/|Collapsible/.test(html))throw Error('Unconverted markup');
const ids=[...body.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
for(const m of body.matchAll(/href="#([^"]+)"/g))if(!ids.includes(m[1]))throw Error('Missing anchor '+m[1]);
for(const phrase of ['Aspiro a ser','Bio <','gran sensibilidad','romántica y neurótica','Mi palabra favorita'])if(body.includes(phrase))throw Error('Previous copy retained: '+phrase);
for(const phrase of ['debilidad por todo','restaurante familiar','salidas laborales.Sin embargo','Instragram (2021 - actualidad)','Substack ( 2026 - actualidad)','QUÉ PUEDES ENCONTRAR EN MIS ARTÍCULOS:','AUTOIRONÍA','COTIDIANIDAD','REFERENCIAS','HUMOR','REFLEXIÓN','SUPONGO QUE DEBERÍA MOSTRARTE ALGUNOS EJEMPLOS, CLARO.','-y el cine-me despedí'])if(!body.includes(phrase))throw Error('Required copy missing: '+phrase);
console.log('Updated standalone HTML; verified '+count+' embedded images, internal links, and revised copy.');
